# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-11 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'tuition', '0001_initial'), (b'tuition', '0002_auto_20160627_2304'), (b'tuition', '0003_auto_20160703_2141'), (b'tuition', '0004_remove_assignment_graded'), (b'tuition', '0005_assignment_due_date'), (b'tuition', '0006_remove_student_assignments'), (b'tuition', '0007_auto_20160711_2331'), (b'tuition', '0002_auto_20160711_2349'), (b'tuition', '0003_auto_20160711_2349'), (b'tuition', '0008_merge_20160711_2355')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('maximum_grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
                ('accepted_students', models.ManyToManyField(related_name='accepted_tutors', to=b'tuition.Student')),
                ('requesting_students', models.ManyToManyField(related_name='requested_tutors', to=b'tuition.Student')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='tuition.Question'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('questions', models.ManyToManyField(related_name='questions', to=b'tuition.Question')),
                ('due_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('UN', 'uncompleted'), ('DO', 'done'), ('RE', 'ready')], default='UN', max_length=2)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TutorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DR', 'draft'), ('RE', 'ready'), ('GR', 'graded'), ('CA', 'cancelled')], default='RE', max_length=2)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.Assignment')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.Tutor')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='assignments',
            field=models.ManyToManyField(related_name='student_assignments', through='tuition.StudentAssignment', to=b'tuition.Assignment'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='assignments',
            field=models.ManyToManyField(related_name='tutor_assignments', through='tuition.TutorAssignment', to=b'tuition.Assignment'),
        ),
    ]
