# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-13 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_squashed_0008_merge_20160711_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='state',
            field=models.CharField(choices=[('UN', 'uncompleted'), ('DO', 'done'), ('GR', 'graded'), ('RE', 'ready')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='tutorassignment',
            name='state',
            field=models.CharField(choices=[('DR', 'draft'), ('RE', 'ready'), ('DO', 'done'), ('GR', 'graded'), ('CA', 'cancelled')], default='RE', max_length=2),
        ),
    ]
