# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_auto_20160627_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='completed_assignments',
        ),
        migrations.RemoveField(
            model_name='student',
            name='due_assignments',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='draft_assignments',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='students',
        ),
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('DR', 'draft'), ('RE', 'ready'), ('DO', 'done'), ('GR', 'graded'), ('VE', 'reviewed')], default='DR', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='assignments',
            field=models.ManyToManyField(related_name='student_assignments', to='tuition.Assignment'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='accepted_students',
            field=models.ManyToManyField(related_name='accepted_tutors', to='tuition.Student'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='requesting_students',
            field=models.ManyToManyField(related_name='requested_tutors', to='tuition.Student'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='assignments',
            field=models.ManyToManyField(related_name='tutor_assignments', to='tuition.Assignment'),
        ),
    ]
