# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-09 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_auto_20160703_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='graded',
        ),
    ]
