# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_remove_assignment_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
