# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-09 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_assignment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assignments',
        ),
    ]
