# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-11 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0007_auto_20160711_2331'),
        ('tuition', '0003_auto_20160711_2349'),
    ]

    operations = [
    ]
